# Server
server.port=8085

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27018
spring.data.mongodb.database=quickmart

# Kafka
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.group-id=quickmart-group
spring.kafka.consumer.auto-offset-reset=earliest

# Logging
logging.level.com.quickmart=INFO